name: CI

on: [push]

jobs:
  ubuntu-example-image:
    name: Ubuntu example image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml:kas/opt/ubuntu.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-ubuntu-example-image
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-ubuntu-iot2050.wic.img
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-ubuntu-iot2050.wic.img.bmap

  ubuntu-rt-example-image:
    name: Ubuntu RT example image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml:kas/opt/ubuntu.yml:kas/opt/preempt-rt.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-ubuntu-example-image-rt
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-ubuntu-iot2050.wic.img
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-ubuntu-iot2050.wic.img.bmap

  bootloaders:
    name: Bootloaders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: ./kas-container build kas-iot2050-boot.yml
      - name: Archive bootloaders
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
