name: CI

on: [push]

jobs:
  ubuntu-example-image:
    name: Ubuntu example image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml:kas/opt/ubuntu.yml
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-ubuntu-iot2050.wic.img
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-ubuntu-iot2050.wic.img.bmap

  bootloaders:
    name: Bootloaders for both PG1 and PG2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build bootloader image for PG1
        run: ./kas-container build kas-iot2050-boot-pg1.yml
      - name: Build bootloader image for PG2
        run: ./kas-container build kas-iot2050-boot-pg2.yml
      - name: Archive bootloaders
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
